image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image:
    name: registry.gitlab.com/pages/hugo:latest
    entrypoint: [""]
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

